<template>
  <!-- <ProPopup
    :class="`com-trial-wrap ${$attrs.class}`"
    :show="isShow"
    :closeable="false"
    @close="onClosePopup"
    @closed="onClosePopupAfterAni"
  > -->
  <div>
    <div class="search-bar">
      <van-search
        v-model="state.keyword"
        shape="round"
        placeholder="客户 姓名/手机号"
        class="icon-sercher"
        @search="handleSearch"
      >
        <template #left-icon>
          <img :src="SearchLeftIcon" alt="" class="search-icon-img" style="width: 22px; height: 23px" />
        </template>
      </van-search>
    </div>
    <List :data="state.list" type="firstLetter" :disabled="false" />
    <div v-if="!state.list?.length" style="padding-top: 50px">
      <!-- <p><img src="@/assets/images/baseInsurance/empth.png" class="ig" /></p> -->
      <ProEmpty :title="loading ? '加载中...' : '暂无客户'" />
    </div>
  </div>
  <!-- </ProPopup> -->
</template>
<script lang="ts" setup name="CustomerList">
import { withDefaults, ref, defineExpose } from 'vue';
import { Toast } from 'vant';
import { useRoute } from 'vue-router';
import { getCustomerList } from '@/api/modules/third';
import SearchLeftIcon from '@/assets/images/baseInsurance/search.png';
import List from './List.vue';

const route = useRoute();
const emit = defineEmits(['closeCustomerPopoup']);
interface StateInfo {
  show: boolean;
  keyword: any;
  list: any;
}
interface Props {
  isShow: boolean;
}
const props = withDefaults(defineProps<Props>(), {
  isShow: true,
});

const state = reactive<Partial<StateInfo>>({
  keyword: undefined,
  show: false,
  list: [],
});
const mockData = {
  count: 112,
  customersMap: {
    A: [],
    B: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        certType: '1',
        certNo: 'afadsfasdfasdf1',
        agentCustomerId: '1074001',
        name: '北京乐',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '3333',
        source: '5',
        openNo: null,
        visitTag: '电话邀约',
        createTime: null,
        firstLetter: 'bei jing le ',
        followTime: '2023-01-06T19:39:38.000+08:00',
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1074004',
        name: '北京乐',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15010877811',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'bei jing le ',
        followTime: '2023-02-06T16:52:53.000+08:00',
        relative: false,
      },
    ],
    C: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662040',
        name: '蔡二',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13770071493',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'cai er ',
        followTime: '2023-02-06T16:52:53.000+08:00',
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662041',
        name: '曹冬建',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18795998919',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'cao dong jian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1068418',
        name: '陈晨',
        customerType: '02',
        visitorId: null,
        gender: '',
        phone: '15084894646',
        source: null,
        openNo: 'o63YPw0HydtYe4HgNLoaDhZ19BTA',
        visitTag: '电话邀约',
        createTime: null,
        firstLetter: 'chen chen ',
        followTime: null,
        relative: true,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1068416',
        name: '陈晓赵',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15001237599',
        source: null,
        openNo: null,
        visitTag: '接触面谈',
        createTime: null,
        firstLetter: 'chen xiao zhao ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662042',
        name: '程卓新',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18616701425',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'cheng zhuo xin ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662043',
        name: '仇焰',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15601599712',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'chou yan ',
        followTime: '2023-01-05T15:19:59.000+08:00',
        relative: false,
      },
    ],
    D: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662044',
        name: '电信营业厅盐东',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '051582650147',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'dian xin ying ye ting yan dong ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662045',
        name: '定牛奶光明',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13222180075',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ding niu nai guang ming ',
        followTime: null,
        relative: false,
      },
    ],
    E: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1068423',
        name: '哦汪洋',
        customerType: '02',
        visitorId: null,
        gender: '',
        phone: '15000000000',
        source: null,
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'e wang yang ',
        followTime: '2023-01-05T14:39:13.000+08:00',
        relative: false,
      },
    ],
    F: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662046',
        name: '房东公安局宿舍楼',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15851399729',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'fang dong gong an ju su she lou ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662048',
        name: '富力城无锡总部',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '051088987777',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'fu li cheng wu xi zong bu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662047',
        name: '富力城无锡总部',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '051088987777',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'fu li cheng wu xi zong bu ',
        followTime: null,
        relative: false,
      },
    ],
    G: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719091',
        name: '公积金',
        customerType: '02',
        visitorId: null,
        gender: '1',
        phone: '15317564555',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'gong ji jin ',
        followTime: null,
        relative: false,
      },
    ],
    H: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719093',
        name: '哈哈还',
        customerType: '02',
        visitorId: null,
        gender: '',
        phone: '13522222225',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'ha ha hai ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662051',
        name: '胡旭东',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18210011301',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'hu xu dong ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662050',
        name: '黄莉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18086798352',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'huang li ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662049',
        name: '黄莉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18086798352',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'huang li ',
        followTime: null,
        relative: false,
      },
    ],
    I: [],
    J: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662052',
        name: '季',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15105103606',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ji ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662056',
        name: '吉剑波',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15189200512',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ji jian bo ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662055',
        name: '吉剑波',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15189200512',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ji jian bo ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662054',
        name: '贾飞',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15150656025',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'jia fei ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662053',
        name: '贾飞',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15150656025',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'jia fei ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662057',
        name: '姜路',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18115182812',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'jiang lu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662058',
        name: '姜路',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18115182812',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'jiang lu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719079',
        name: '叫啊叫',
        customerType: '02',
        visitorId: null,
        gender: '1',
        phone: '15317327222',
        source: '6',
        openNo: 'o63YPw4FBYpHZPuc9KUBnJtSKhxo',
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'jiao a jiao ',
        followTime: '2023-01-05T14:42:18.000+08:00',
        relative: true,
      },
    ],
    K: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1729012',
        name: '卡不卡',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15388556665',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'ka bu ka ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719088',
        name: '看看',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15325467955',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'kan kan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662061',
        name: '孔玲。。',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18921815238',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'kong ling 。 。 ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662062',
        name: '孔玲。。',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18921815238',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'kong ling 。 。 ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662059',
        name: '快件小潘',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '66860',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'kuai jian xiao pan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662060',
        name: '快件小潘',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '66860',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'kuai jian xiao pan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719074',
        name: '困了吗',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15317558845',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'kun le ma ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719075',
        name: '困了吗',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15317327376',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'kun le ma ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719082',
        name: '困了吗',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15317657546',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'kun le ma ',
        followTime: null,
        relative: false,
      },
    ],
    L: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719090',
        name: '老了老了',
        customerType: '02',
        visitorId: null,
        gender: '1',
        phone: '15345677999',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'lao le lao le ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1729002',
        name: '邻居',
        customerType: '02',
        visitorId: null,
        gender: '1',
        phone: '19912341234',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'lin ju ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1729001',
        name: '邻居家',
        customerType: '02',
        visitorId: null,
        gender: '1',
        phone: '18866661111',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'lin ju jia ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662068',
        name: '刘小庆',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15601599690',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'liu xiao qing ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662067',
        name: '刘小庆',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15601599690',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'liu xiao qing ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662066',
        name: '刘主任',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '692369',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'liu zhu ren ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662065',
        name: '刘主任',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '692369',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'liu zhu ren ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662063',
        name: '陆树嘉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15501692903',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'lu shu jia ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662064',
        name: '陆树嘉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15501692903',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'lu shu jia ',
        followTime: null,
        relative: false,
      },
    ],
    M: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662071',
        name: '梅陇链家',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18321522049',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'mei long lian jia ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662069',
        name: '梅陇链家',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18321522049',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'mei long lian jia ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662070',
        name: '梅陇链家',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18321522049',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'mei long lian jia ',
        followTime: null,
        relative: false,
      },
    ],
    N: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662073',
        name: '农业银行黄埔',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '02120733715',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'nong ye yin xing huang pu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662072',
        name: '农业银行黄埔',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '02120733715',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'nong ye yin xing huang pu ',
        followTime: null,
        relative: false,
      },
    ],
    O: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1727077',
        name: '欧美',
        customerType: '02',
        visitorId: null,
        gender: '1',
        phone: '15315646466',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'ou mei ',
        followTime: null,
        relative: false,
      },
    ],
    P: [],
    Q: [],
    R: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662075',
        name: '仁平安保险',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '1109662901001078643',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ren ping an bao xian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662074',
        name: '仁平安保险',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '1109662901001078643',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ren ping an bao xian ',
        followTime: null,
        relative: false,
      },
    ],
    S: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662076',
        name: '收废品',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13774431549',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'shou fei pin ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662077',
        name: '收废品',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13774431549',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'shou fei pin ',
        followTime: null,
        relative: false,
      },
    ],
    T: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662079',
        name: '亭湖医保',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '051588303478',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ting hu yi bao ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662080',
        name: '亭湖医保',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '051588303478',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ting hu yi bao ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662078',
        name: '亭湖医保',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '051588303478',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'ting hu yi bao ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719076',
        name: '通行证',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15317327569',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'tong xing zheng ',
        followTime: '2023-01-05T14:40:34.000+08:00',
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719089',
        name: '桶装',
        customerType: '02',
        visitorId: null,
        gender: '1',
        phone: '15345668788',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'tong zhuang ',
        followTime: null,
        relative: false,
      },
    ],
    U: [],
    V: [],
    W: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662093',
        name: 'Worktile',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '4008056966',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'W o r k t i l e ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662092',
        name: 'Worktile',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '4008056966',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'W o r k t i l e ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662094',
        name: 'Worktile',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '4008056966',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'W o r k t i l e ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1719083',
        name: '王大伟',
        customerType: '02',
        visitorId: null,
        gender: '2',
        phone: '15317864956',
        source: '4',
        openNo: null,
        visitTag: '客户获取',
        createTime: null,
        firstLetter: 'wang da wei ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662090',
        name: '王瑾',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18251424750',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wang jin ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662091',
        name: '王瑾',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18251424750',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wang jin ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662084',
        name: '卫成',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15195977787',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wei cheng ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662088',
        name: '维乐口腔马医生助理',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18501633286',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wei le kou qiang ma yi sheng zhu li ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662086',
        name: '维乐口腔马医生助理',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18501633286',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wei le kou qiang ma yi sheng zhu li ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662087',
        name: '维乐口腔马医生助理',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18501633286',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wei le kou qiang ma yi sheng zhu li ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662089',
        name: '维乐口腔马医生助理',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18501633286',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wei le kou qiang ma yi sheng zhu li ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662081',
        name: '物流上海盐城，木泰宾馆对面',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13705104640',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wu liu shang hai yan cheng ， mu tai bin guan dui mian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662082',
        name: '物流上海盐城，木泰宾馆对面',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13705104640',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wu liu shang hai yan cheng ， mu tai bin guan dui mian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662083',
        name: '物流上海盐城，木泰宾馆对面',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13705104640',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wu liu shang hai yan cheng ， mu tai bin guan dui mian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662085',
        name: '吴倩倩。',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13476240568',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'wu qian qian 。 ',
        followTime: null,
        relative: false,
      },
    ],
    X: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662095',
        name: '徐伟琴',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13482239261',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'xu wei qin ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662096',
        name: '徐伟琴',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13482239261',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'xu wei qin ',
        followTime: null,
        relative: false,
      },
    ],
    Y: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662110',
        name: '杨坤号',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13770002122',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yang kun hao ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662108',
        name: '杨坤号',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13770002122',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yang kun hao ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662109',
        name: '杨坤号',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13770002122',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yang kun hao ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662097',
        name: '易信专线',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18757141666',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yi xin zhuan xian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662098',
        name: '易信专线',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18757141666',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yi xin zhuan xian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662099',
        name: '易信专线',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18757141666',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yi xin zhuan xian ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662105',
        name: '玉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18874911656',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662106',
        name: '玉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18874911656',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662104',
        name: '玉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18874911656',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662107',
        name: '玉',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '18874911656',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662103',
        name: '于丹红',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15605157990',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu dan hong ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662102',
        name: '于丹红',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15605157990',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu dan hong ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662100',
        name: '虞勇宾',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15251895372',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu yong bin ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662101',
        name: '虞勇宾',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15251895372',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'yu yong bin ',
        followTime: null,
        relative: false,
      },
    ],
    Z: [
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662126',
        name: '甄汇',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13764072019',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhen hui ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662125',
        name: '甄汇',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '13764072019',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhen hui ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662123',
        name: '中南全屋定制',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '17351552361',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhong nan quan wu ding zhi ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662121',
        name: '中南全屋定制',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '17351552361',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhong nan quan wu ding zhi ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662124',
        name: '中南全屋定制',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '17351552361',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhong nan quan wu ding zhi ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662122',
        name: '中南全屋定制',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '17351552361',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhong nan quan wu ding zhi ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662120',
        name: '中南全屋定制',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '17351552361',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhong nan quan wu ding zhi ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662119',
        name: '中兴客服',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '4008809999',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhong xing ke fu ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662118',
        name: '周国稳',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '66445',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhou guo wen ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662116',
        name: '周国稳',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '66445',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhou guo wen ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662117',
        name: '周国稳',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '66445',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhou guo wen ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662114',
        name: '周国稳',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '66445',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhou guo wen ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662115',
        name: '周国稳',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '66445',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhou guo wen ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662113',
        name: '朱春山',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15195977805',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhu chun shan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662111',
        name: '朱春山',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15195977805',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhu chun shan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662112',
        name: '朱春山',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '15195977805',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhu chun shan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662130',
        name: '专利李锬',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '02551862105',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhuan li li tan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662128',
        name: '专利李锬',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '02551862105',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhuan li li tan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662131',
        name: '专利李锬',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '02551862105',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhuan li li tan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662127',
        name: '专利李锬',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '02551862105',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhuan li li tan ',
        followTime: null,
        relative: false,
      },
      {
        id: null,
        tenantId: 9991000007,
        userId: null,
        agentCustomerId: '1662129',
        name: '专利李锬',
        customerType: '02',
        visitorId: null,
        gender: null,
        phone: '02551862105',
        source: '5',
        openNo: null,
        visitTag: null,
        createTime: null,
        firstLetter: 'zhuan li li tan ',
        followTime: null,
        relative: false,
      },
    ],
  },
};
const loading = ref(false);
const getData = async (params: { [key: string]: string }) => {
  if (loading.value) return;
  loading.value = true;
  Toast.loading('加载中...');
  const reqs = {
    pageNum: 1,
    pageSize: 999,
    accessKey: 'ToDo', // TODO @za-qixuchao
    keyword: state.keyword || '',
    relation: route.query.relation,
    ...params,
  };
  getCustomerList(reqs)
    .then((res) => {
      const temp: { label: string; children: any }[] = [];

      Object.keys(res.data?.customersMap || {}).forEach((item) => {
        temp.push({
          label: item,
          children: res.data.customersMap[item],
        });
      });
      state.list = temp;
    })
    .finally(() => {
      loading.value = false;
      Toast.clear();
    });
};

onBeforeMount(() => {
  console.log('111122');
  getData({ keyword: '' });
});
onMounted(() => {
  console.log('3333');
});
// 搜索
const handleSearch = () => {
  getData({ keyword: state.keyword });
};
</script>
