export default {};
export const insureProductDetail = {
  status: 'OK',
  code: '10000',
  message: '成功响应',
  data: {
    productBasicInfoVO: {
      id: 771,
      productCode: 'CEB013',
      productName: '北大方正人寿健康保两全保险',
      productFullName: '北大方正人寿健康保两全保险',
      insurerCode: 'beidafangzhenglife',
      insurerName: '北大方正人寿保险有限公司',
      productCategory: 5,
      combinationFlag: 2,
      insureMethod: 'API',
      extInfo: '',
      premiumCalcType: 2,
    },
    productMaterialVOList: [
      {
        id: 12919,
        productId: 771,
        materialType: null,
        materialTypeDesc: null,
        materialSource: 1,
        materialSourceDesc: '附件',
        materialContent: 'common/20230204/f6766279c6384a62a204341ef5b24a6d/责任免除条款说明书.pdf',
        noticeObject: null,
        noticeObjectDesc: null,
      },
      {
        id: 12920,
        productId: 771,
        materialType: null,
        materialTypeDesc: null,
        materialSource: 1,
        materialSourceDesc: '附件',
        materialContent:
          'common/20230204/67a08f0be0a7448aba2681dd3108bf8a/众安在线财产保险股份有限公司附加猝死保险条款（互联网）.pdf',
        noticeObject: null,
        noticeObjectDesc: null,
      },
      {
        id: 12921,
        productId: 771,
        materialType: null,
        materialTypeDesc: null,
        materialSource: 1,
        materialSourceDesc: '附件',
        materialContent:
          'common/20230204/c83d64e1a61c40249c1498895617e938/众安在线财产保险股份有限公司附加意外伤害医疗费用保险条款（互联网2022版A款）.pdf',
        noticeObject: null,
        noticeObjectDesc: null,
      },
    ],
    productRiskVoList: [
      {
        riskDetailVOList: [
          {
            id: 287,
            insurerCode: 'beidafangzhenglife',
            insurerName: '北大方正人寿保险有限公司',
            riskCode: 'CEB013',
            riskName: '北大方正人寿健康保两全保险',
            riskCategory: 5,
            riskCategoryDesc: '寿险',
            circCategory: '1',
            circCategoryDesc: '人寿保险',
            liabilityPlanOssUrl: null,
            riskType: 1,
            mainRiskId: null,
            mainRiskCode: null,
            riskTypeDesc: '主险',
            periodType: 1,
            periodTypeDesc: '长期',
            exemptFlag: 2,
            exemptType: null,
            exemptTypeDesc: null,
            configStatus: 2,
            relationDesc: null,
            extraInfo: '{}',
            riskInsureLimitVO: {
              id: 278,
              riskId: 287,
              sexLimit: '-1',
              socialInsuranceLimit: '-1',
              occupationLimitList: ['-1'],
              minHolderAge: 'day_7',
              maxHolderAge: 'age_65',
              toLifeAge: null,
              paymentFrequencyList: ['1', '2'],
              paymentPeriodType: 2,
              paymentPeriodValueList: ['year_10', 'year_15', 'year_20', 'year_5', 'single'],
              insurancePeriodType: 2,
              insurancePeriodValueList: ['to_68', 'to_78', 'to_88'],
              insuredNum: null,
              insurancePeriodRule: null,
              paymentPeriodRule: null,
              paymentTypeRule: null,
              annuityDrawType: 2,
              annuityDrawValueList: null,
              annuityDrawFrequencyList: null,
            },
            riskCalcMethodInfoVO: {
              id: 248,
              riskId: 287,
              saleMethod: 1,
              saleMethodDesc: null,
              calculateType: null,
              calculateTypeDesc: null,
              singePremium: null,
              singeAmount: null,
              minCopy: null,
              maxCopy: null,
              increaseDecreaseNum: 1000,
              fixedAmount: 0,
              paymentMethodLimitList: [
                {
                  riskId: 287,
                  paymentFrequency: 1,
                  minAmount: 50000,
                  maxAmount: null,
                  minPremium: null,
                  maxPremium: null,
                  perCopyAmount: null,
                  perCopyPremium: null,
                },
                {
                  riskId: 287,
                  paymentFrequency: 2,
                  minAmount: 50000,
                  maxAmount: null,
                  minPremium: null,
                  maxPremium: null,
                  perCopyAmount: null,
                  perCopyPremium: null,
                },
              ],
              dataTableList: [
                'https://zatech-aquarius-v2-private-test.oss-cn-hangzhou.aliyuncs.com/planetOssFile/202211101727422804e081e13a2f3484dbe7a9865054a0c0f/%E5%8C%97%E5%A4%A7%E6%96%B9%E6%AD%A3%E4%B8%A4%E5%85%A8%E4%BF%9D%E9%99%A9%E8%B4%B9%E7%8E%87%E8%A1%A8%20%281%29.csv?Expires=1675508837&OSSAccessKeyId=LTAI5t9uBW78vZ4sm5i3oQ5C&Signature=aiHnLRuTyPPW9vAH6%2BSRwUwQtsc%3D',
              ],
              riskFormulaRelationList: [
                {
                  id: 274,
                  riskId: 287,
                  formulaName: '计算保费内置公式',
                  formulaType: '2',
                  liabilityId: null,
                  formulaCode: 'PREM001',
                },
              ],
              riskFactorRelationList: [
                {
                  id: 806,
                  riskId: 287,
                  factorCode: 'PAY_CODE',
                  factorObject: 'risk',
                  businessType: 1,
                  factorName: '缴费期间',
                },
                {
                  id: 807,
                  riskId: 287,
                  factorCode: 'INSURE_CODE',
                  factorObject: 'risk',
                  businessType: 1,
                  factorName: '保障期间',
                },
                {
                  id: 808,
                  riskId: 287,
                  factorCode: 'AGE',
                  factorObject: 'insured',
                  businessType: 1,
                  factorName: '被保人年龄',
                },
                {
                  id: 809,
                  riskId: 287,
                  factorCode: 'GENDER',
                  factorObject: 'insured',
                  businessType: 1,
                  factorName: '被保人性别',
                },
              ],
            },
            riskFactorLinkAgeInfoVOList: [
              {
                id: 416,
                riskId: 287,
                paymentPeriod: 'single',
                insurancePeriod: 'to_68',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_50',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 417,
                riskId: 287,
                paymentPeriod: 'single',
                insurancePeriod: 'to_78',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_60',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 418,
                riskId: 287,
                paymentPeriod: 'single',
                insurancePeriod: 'to_88',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_65',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 419,
                riskId: 287,
                paymentPeriod: 'year_5',
                insurancePeriod: 'to_68',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_45',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 420,
                riskId: 287,
                paymentPeriod: 'year_5',
                insurancePeriod: 'to_78',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_55',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 421,
                riskId: 287,
                paymentPeriod: 'year_5',
                insurancePeriod: 'to_88',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_60',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 422,
                riskId: 287,
                paymentPeriod: 'year_10',
                insurancePeriod: 'to_68',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_45',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 423,
                riskId: 287,
                paymentPeriod: 'year_10',
                insurancePeriod: 'to_78',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_50',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 424,
                riskId: 287,
                paymentPeriod: 'year_10',
                insurancePeriod: 'to_88',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_55',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 425,
                riskId: 287,
                paymentPeriod: 'year_15',
                insurancePeriod: 'to_68',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_40',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 426,
                riskId: 287,
                paymentPeriod: 'year_15',
                insurancePeriod: 'to_78',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_45',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 427,
                riskId: 287,
                paymentPeriod: 'year_15',
                insurancePeriod: 'to_88',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_50',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 428,
                riskId: 287,
                paymentPeriod: 'year_20',
                insurancePeriod: 'to_78',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_40',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
              {
                id: 429,
                riskId: 287,
                paymentPeriod: 'year_20',
                insurancePeriod: 'to_88',
                minHolderAge: 'day_7',
                maxHolderAge: 'age_45',
                annuityDrawDate: null,
                annuityDrawDateDesc: null,
              },
            ],
            riskRuleInfoVOList: [
              {
                id: 131,
                riskId: 287,
                ruleName: '成年人保额最高200万',
                ruleParams: '',
                ruleCondition: 'AGE >= 18 and AMOUNT >2000000',
                ruleTip: '成年人保额最高200万',
              },
              {
                id: 132,
                riskId: 287,
                ruleName: '未成年人保额最高60万',
                ruleParams: '',
                ruleCondition: 'AGE < 18 and AMOUNT > 600000',
                ruleTip: '未成年人保额最高60万',
              },
            ],
            riskLiabilityInfoVOList: [
              {
                id: 658,
                riskId: 287,
                liabilityId: 235,
                liabilityName: '满期生存保险金',
                liabilityCode: 'MQSC',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc:
                  '被保人在合同期满时仍生存，满期时合同未附加相关重疾保险，给付合同期满时的满期保险金额；期满时合同附加了相关重疾保险，给付（合同的已交保费+附加重疾保险的已交保费）X135%',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
              {
                id: 659,
                riskId: 287,
                liabilityId: 234,
                liabilityName: '意外身故保险金',
                liabilityCode: 'YWSG',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc: '给付身故保险金的同时，还按合同的基本保额给付意外身故保险金',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
              {
                id: 660,
                riskId: 287,
                liabilityId: 233,
                liabilityName: '身故、全残保险金',
                liabilityCode: 'SGBXJ',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc:
                  '未满18周岁100%（已交保费X对应给付比例，现金价值） 已满18周岁但未满41周岁160%（已交保费X对应给付比例，现金价值） 已满41周岁但未满61周岁140%（已交保费X对应给付比例，现金价值） 已满61周岁120%（已交保费X对应给付比例，现金价值）',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
            ],
            collocationVOList: [],
            collocationType: null,
            riskAttachmentVOList: [
              {
                businessType: 'PRODUCT_TERMS',
                attachmentType: 'PDF',
                attachmentName: '健康保两全保险保险条款.pdf',
                attachmentUrl:
                  'https://zatech-aquarius-v2-private-test.oss-cn-hangzhou.aliyuncs.com/planetOssFile/20221110170526160262b17aa20c540109f4b281dbefdd6af/%E5%81%A5%E5%BA%B7%E4%BF%9D%E4%B8%A4%E5%85%A8%E4%BF%9D%E9%99%A9%E4%BF%9D%E9%99%A9%E6%9D%A1%E6%AC%BE.pdf?Expires=1676113398&OSSAccessKeyId=LTAI5t9uBW78vZ4sm5i3oQ5C&Signature=2gwWdeKRIpF9F2%2FDl4sdufQqW6c%3D',
              },
            ],
          },
          {
            id: 302,
            insurerCode: 'beidafangzhenglife',
            insurerName: '北大方正人寿保险有限公司',
            riskCode: 'CDR020',
            riskName: '附加健康保重大疾病保险',
            riskCategory: 2,
            riskCategoryDesc: '重疾险',
            circCategory: '1',
            circCategoryDesc: '人寿保险',
            liabilityPlanOssUrl: null,
            riskType: 2,
            mainRiskId: 287,
            mainRiskCode: 'CEB013',
            riskTypeDesc: '附加险',
            periodType: 1,
            periodTypeDesc: '长期',
            exemptFlag: 2,
            exemptType: null,
            exemptTypeDesc: null,
            configStatus: 2,
            relationDesc: null,
            extraInfo: '{}',
            riskInsureLimitVO: {
              id: 293,
              riskId: 302,
              sexLimit: '-1',
              socialInsuranceLimit: '-1',
              occupationLimitList: ['-1'],
              minHolderAge: 'day_7',
              maxHolderAge: 'age_65',
              toLifeAge: null,
              paymentFrequencyList: null,
              paymentPeriodType: 2,
              paymentPeriodValueList: null,
              insurancePeriodType: 2,
              insurancePeriodValueList: null,
              insuredNum: null,
              insurancePeriodRule: 1,
              paymentPeriodRule: 1,
              paymentTypeRule: 1,
              annuityDrawType: 2,
              annuityDrawValueList: null,
              annuityDrawFrequencyList: null,
            },
            riskCalcMethodInfoVO: {
              id: 263,
              riskId: 302,
              saleMethod: 1,
              saleMethodDesc: null,
              calculateType: null,
              calculateTypeDesc: null,
              singePremium: null,
              singeAmount: null,
              minCopy: null,
              maxCopy: null,
              increaseDecreaseNum: 1000,
              fixedAmount: 0,
              paymentMethodLimitList: [
                {
                  riskId: 302,
                  paymentFrequency: 0,
                  minAmount: 50000,
                  maxAmount: 2000000,
                  minPremium: null,
                  maxPremium: null,
                  perCopyAmount: null,
                  perCopyPremium: null,
                },
              ],
              dataTableList: [
                'https://zatech-aquarius-v2-private-test.oss-cn-hangzhou.aliyuncs.com/planetOssFile/20221111154327925c3224f8631314277854de97188ca3730/%E5%8C%97%E5%A4%A7%E6%96%B9%E6%AD%A3%E9%99%84%E5%8A%A0%E5%81%A5%E5%BA%B7%E4%BF%9D%E9%87%8D%E5%A4%A7%E7%96%BE%E7%97%85%E4%BF%9D%E9%99%A9%E8%B4%B9%E7%8E%87%E8%A1%A8.csv?Expires=1675508850&OSSAccessKeyId=LTAI5t9uBW78vZ4sm5i3oQ5C&Signature=JFRjTBC65mTs3QchfTYk2qrXfpE%3D',
              ],
              riskFormulaRelationList: [
                {
                  id: 275,
                  riskId: 302,
                  formulaName: '计算保费内置公式',
                  formulaType: '2',
                  liabilityId: null,
                  formulaCode: 'PREM001',
                },
              ],
              riskFactorRelationList: [
                {
                  id: 810,
                  riskId: 302,
                  factorCode: 'PAY_CODE',
                  factorObject: 'risk',
                  businessType: 1,
                  factorName: '缴费期间',
                },
                {
                  id: 811,
                  riskId: 302,
                  factorCode: 'INSURE_CODE',
                  factorObject: 'risk',
                  businessType: 1,
                  factorName: '保障期间',
                },
                {
                  id: 812,
                  riskId: 302,
                  factorCode: 'GENDER',
                  factorObject: 'insured',
                  businessType: 1,
                  factorName: '被保人性别',
                },
                {
                  id: 813,
                  riskId: 302,
                  factorCode: 'AGE',
                  factorObject: 'insured',
                  businessType: 1,
                  factorName: '被保人年龄',
                },
              ],
            },
            riskFactorLinkAgeInfoVOList: null,
            riskRuleInfoVOList: [
              {
                id: 139,
                riskId: 302,
                ruleName: '已满18周岁保额',
                ruleParams: '',
                ruleCondition: 'AGE >= 18 and AMOUNT >2000000',
                ruleTip: '已满18周岁保额最高200万',
              },
              {
                id: 140,
                riskId: 302,
                ruleName: '未满18周岁保额',
                ruleParams: '',
                ruleCondition: 'AGE < 18 and AMOUNT > 600000',
                ruleTip: '未满18周岁，最高保额不可超过60万',
              },
            ],
            riskLiabilityInfoVOList: [
              {
                id: 661,
                riskId: 302,
                liabilityId: 245,
                liabilityName: '重大疾病保险金',
                liabilityCode: 'ZDJB',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc:
                  '110种，6组，每组赔一次 第一次重大疾病保险金：等待期后确诊，max（基本保险金额，主附险ROP之和，主附险现金价值之和），给付后本组疾病责任结束，主险责任结束； 第二次重大疾病保险金：给付100%基本保额，给付后本组疾病责任结束； 第三次重大疾病保险金：给付100%基本保额，给付后本组疾病责任结束； 第四次重大疾病保险金：给付100%基本保额，给付后本组疾病责任结束； 第五次重大疾病保险金：给付100%基本保额，给付后本组疾病责任结束； 第六次重大疾病保险金：给付100%基本保额，给付后本组疾病责任结束，主险合同终止',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
              {
                id: 662,
                riskId: 302,
                liabilityId: 246,
                liabilityName: '中症疾病保险金',
                liabilityCode: 'ZZJB',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc: '20种不分组，50%基本保额，最高给付2次，合同继续有效',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
              {
                id: 663,
                riskId: 302,
                liabilityId: 247,
                liabilityName: '轻症疾病保险金',
                liabilityCode: 'QZJB',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc: '50种不分组，30%基本保额，最高给付3次，合同继续有效',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
              {
                id: 664,
                riskId: 302,
                liabilityId: 248,
                liabilityName: '轻中重症豁免保险费',
                liabilityCode: 'HMBF',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc: '发生首次轻症、中症或重疾即豁免主附险剩余各期保险费，合同继续有效',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
              {
                id: 665,
                riskId: 302,
                liabilityId: 244,
                liabilityName: '身故、全残保险金',
                liabilityCode: 'SGQC',
                optionFlag: null,
                amountCalculateType: null,
                amountCalculateTypeDesc: null,
                premiumCalculateType: null,
                premiumCalculateDesc: null,
                premium: null,
                amount: null,
                optionalFlag: 1,
                optionalFlagDesc: null,
                liabilityDesc:
                  '未满18周岁，主合同和本附加合同的所有已交的保险费/主合同和本附加合同的现金价值最大值减去主合同已给付的身故/全残保险金差额 已满18周岁，主合同和本附加合同的所有已交的保险费/主合同和本附加合同的现金价值/本附加合同的基本保险金额最大值减去主合同已给付的身故/全残保险金差额',
                extraInfo: null,
                liabilityAttributeType: null,
                liabilityAttributeValueList: null,
                liabilityRateType: 2,
                liabilityTopType: null,
                liabilityType: null,
                liabilityIndemnityType: null,
                liabilityIndemnityContent: null,
              },
            ],
            collocationVOList: null,
            collocationType: 1,
            riskAttachmentVOList: [
              {
                businessType: 'PRODUCT_TERMS',
                attachmentType: 'PDF',
                attachmentName: '附加健康保重大疾病保险保险条款.pdf',
                attachmentUrl:
                  'https://zatech-aquarius-v2-private-test.oss-cn-hangzhou.aliyuncs.com/planetOssFile/2022111115310244245b630db1eb848f7a2b7b6f41b3c8977/%E9%99%84%E5%8A%A0%E5%81%A5%E5%BA%B7%E4%BF%9D%E9%87%8D%E5%A4%A7%E7%96%BE%E7%97%85%E4%BF%9D%E9%99%A9%E4%BF%9D%E9%99%A9%E6%9D%A1%E6%AC%BE.pdf?Expires=1676113398&OSSAccessKeyId=LTAI5t9uBW78vZ4sm5i3oQ5C&Signature=cmIMI9e%2BD6sjXpVlQ2XZ%2BcTAxng%3D',
              },
            ],
          },
        ],
      },
    ],
    productRelationPlanVOList: [],
  },
  date: 1675508600808,
  success: true,
  ok: true,
};
