<template><h2 id="介绍" tabindex="-1"><a class="header-anchor" href="#介绍" aria-hidden="true">#</a> 介绍</h2>
<ul>
<li>代码目录： views/customer</li>
<li>功能罗列：（功能少的这里可以不要）
<ul>
<li>客户列表</li>
<li>详情</li>
<li>关联客户</li>
<li>创建客户</li>
<li>拜访记录</li>
<li>其他等等</li>
</ul>
</li>
</ul>
<h2 id="客户列表" tabindex="-1"><a class="header-anchor" href="#客户列表" aria-hidden="true">#</a> 客户列表</h2>
<ul>
<li>这里描述
<blockquote>
<p>功能的描述</p>
</blockquote>
</li>
<li>这里放截图
<blockquote>
<p>放一个截图</p>
</blockquote>
</li>
<li>重要注意点</li>
</ul>
<h2 id="客户详情" tabindex="-1"><a class="header-anchor" href="#客户详情" aria-hidden="true">#</a> 客户详情</h2>
<ul>
<li>这里描述
<blockquote>
<p>功能的描述</p>
</blockquote>
</li>
<li>这里放截图
<blockquote>
<p>放一个截图</p>
</blockquote>
</li>
<li>重要注意点
如果下面还有比较详细的</li>
</ul>
<h3 id="拜访记录" tabindex="-1"><a class="header-anchor" href="#拜访记录" aria-hidden="true">#</a> 拜访记录</h3>
<ul>
<li>这里拜访记录描述
<blockquote>
<p>功能的描述</p>
</blockquote>
</li>
<li>这里放截图
<blockquote>
<p>放一个截图</p>
</blockquote>
</li>
<li>重要注意点
<ul>
<li>总共七个步骤</li>
<li>步骤一</li>
<li>步骤二</li>
<li>步骤三、、、、</li>
</ul>
</li>
</ul>
<h3 id="互动记录" tabindex="-1"><a class="header-anchor" href="#互动记录" aria-hidden="true">#</a> 互动记录</h3>
<ul>
<li>这里拜访记录描述
<blockquote>
<p>功能的描述</p>
</blockquote>
</li>
<li>这里放截图
<blockquote>
<p>放一个截图</p>
</blockquote>
</li>
<li>重要注意点</li>
</ul>
<h2 id="客户关联" tabindex="-1"><a class="header-anchor" href="#客户关联" aria-hidden="true">#</a> 客户关联</h2>
<ul>
<li>这里描述
<blockquote>
<p>功能的描述</p>
</blockquote>
</li>
<li>这截图
<blockquote>
<p>放一个截图</p>
</blockquote>
</li>
<li>重要注意点</li>
</ul>
<p>关联</p>
<table>
<thead>
<tr>
<th>sdf</th>
<th>adf</th>
</tr>
</thead>
<tbody>
<tr>
<td>222</td>
<td>fsdf</td>
</tr>
</tbody>
</table>
</template>
