// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  // 开发时去掉组件按需引入，直接全量引入，免得热更新呗影响 和 代码容易冲突问题
  export interface GlobalComponents {
    VanButton: typeof import('vant/es')['Button']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanImage: typeof import('vant/es')['Image']
    VanUploader: typeof import('vant/es')['Uploader']
    ZaMap: typeof import('./components/ZaMap/index.vue')['default']
    ZaSvg: typeof import('./components/ZaSvg/index.vue')['default']
    VanProgress: typeof import('vant/es')['Progress']

  }
}

export { }
